[application]
name = "kratos-selfservice-rust"
asset_dir = "public"
out_dir = "dist"

[bundle]
copyright = "Justin's Engineering Services, LLC"
identifier = "com.justinsengineering"
publisher = "Justin's Engineering Services, LLC"
icon = ["assets/favicon.ico"]

[web.app]
# HTML title tag content
title = "Kratos"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
